// Generates the API reference tab: one page per endpoint, grouped into the
// categories in scripts/reference.config.json, from the vendored spec
// (api-reference/openapi.json), the live catalog (see scripts/catalog.ts) and the
// example responses in scripts/responses/ (see scripts/gen-responses.ts).
// Run with `bun scripts/gen-reference.ts`.
// Each endpoint page has the same parts: an opening, Request, Response, Options,
// Cost and limits, and Next. The wording that cannot be derived (what `data`
// holds, which fields need a note, option text, next links) lives in
// scripts/reference.config.json.
// Every api-reference/endpoint/*.mdx it writes is overwritten on each run:
// edit the config, not the output. It only touches api-reference/** and the
// "API Reference" tab in docs.json; sources/*.mdx and the "What you can get"
// nav group belong to builder-docs.

import { readFileSync } from "node:fs";
import { type Json, type JsonObject, fetchCatalog, isObject } from "./catalog";
import { type ExampleResponse, body, problems } from "./page-text";

// reference.config.json also carries slug, intro, example and live fields
// per area for builder-docs's sources/*.mdx pages. This script only reads
// the fields it needs to group endpoint pages into categories.
interface Area {
  title: string;
  icon: string;
  endpoints: string[];
}

interface Config {
  sources: Record<string, string>;
  titles: Record<string, string>;
  areas: Area[];
  notes: Record<string, string>;
  holds: Record<string, string>;
  bestWhenNotes: Record<string, string>;
  requests: Record<string, string>;
  cursorHours: Record<string, number>;
  pagingNotes: Record<string, string>;
  fields: Record<string, string>;
  fieldsFor: Record<string, Record<string, string>>;
  optionText: Record<string, string>;
  optionRewrites: Record<string, string>;
  labels: Record<string, string>;
  optionValues: Record<string, string>;
  next: Record<string, string[]>;
}

interface Operation {
  id: string;
  method: "GET" | "POST";
  path: string;
  slug: string;
  summary: string;
  source: string;
  credits: number | undefined;
  creditsMax: number | undefined;
  terms: string | undefined;
  pages: "cursor" | "page" | undefined;
  input: JsonObject | undefined;
  example: JsonObject | undefined;
  data: JsonObject | undefined;
}

const root = new URL("..", import.meta.url);
const file = (path: string) => new URL(path, root);
const SPEC_PATH = "api-reference/openapi.json";
const GENERATED = "{/* Generated by scripts/gen-reference.ts from api-reference/openapi.json. Do not edit. */}";

const spec = (await Bun.file(file(SPEC_PATH)).json()) as JsonObject;
const catalogList = (await fetchCatalog()).endpoints;
const catalogById = new Map(catalogList.map((endpoint) => [endpoint.id, endpoint]));
const config = (await Bun.file(file("scripts/reference.config.json")).json()) as Config;

// A source is the first part of the id, or the first two when the config names
// them, like google.maps or tiktok.shop.
function sourceOf(parts: string[]): string {
  const two = parts.slice(0, 2).join(".");
  return config.sources[two] === undefined ? (parts[0] ?? two) : two;
}

function operations(): Operation[] {
  const paths = spec.paths as JsonObject;
  const list: Operation[] = [];
  for (const [path, item] of Object.entries(paths)) {
    if (!isObject(item)) continue;
    for (const [method, op] of Object.entries(item)) {
      if (!isObject(op)) continue;
      const parts = path.replace(/^\/v1\//, "").split("/");
      const id = parts.join(".");
      const body = (op.requestBody as JsonObject | undefined)?.content as JsonObject | undefined;
      const json = body?.["application/json"] as JsonObject | undefined;
      const input = json?.schema as JsonObject | undefined;
      const example = isObject(json?.example) ? json.example : undefined;
      const ok = ((op.responses as JsonObject)["200"] as JsonObject | undefined)?.content as JsonObject | undefined;
      const envelope = (ok?.["application/json"] as JsonObject | undefined)?.schema as JsonObject | undefined;
      const data = (envelope?.properties as JsonObject | undefined)?.data as JsonObject | undefined;
      list.push({
        id,
        method: method.toUpperCase() as "GET" | "POST",
        path,
        slug: parts.join("-"),
        summary: typeof op.summary === "string" ? op.summary : id,
        source: sourceOf(parts),
        credits: typeof op["x-credits"] === "number" ? op["x-credits"] : undefined,
        creditsMax: typeof op["x-credits-max"] === "number" ? op["x-credits-max"] : undefined,
        terms: typeof op.description === "string" ? op.description : undefined,
        pages: propertiesOf(input).includes("cursor") ? "cursor" : propertiesOf(input).includes("page") ? "page" : undefined,
        input,
        example,
        data,
      });
    }
  }
  return list;
}

const plural = (count: number, word: string) => `${count} ${word}${count === 1 ? "" : "s"}`;

const isVariable = (op: Operation) =>
  op.credits !== undefined && op.creditsMax !== undefined && op.creditsMax > op.credits;

function cost(op: Operation): string {
  if (op.credits === undefined) return "Free";
  return isVariable(op) ? `From ${plural(op.credits, "credit")}` : plural(op.credits, "credit");
}

const CATALOG_DESCRIPTION =
  "List every Stophy endpoint with its input schema, credit cost, and whether it works without a key. Use it to pick the right call.";

const quote = (text: string) => text.replaceAll("'", "''");

function sourceName(op: Operation): string {
  const name = config.sources[op.source];
  if (name === undefined) throw new Error(`No display name for source ${op.source}`);
  return name;
}

function endpointTitle(op: Operation): string {
  const title = config.titles[op.id];
  if (title === undefined) throw new Error(`No title for ${op.id} in reference.config.json`);
  return title;
}

const PROPER_NOUNS: string[] = [];

const lowerFirst = (text: string) =>
  /^[A-Z][a-z]/.test(text) && !PROPER_NOUNS.some((noun) => text.startsWith(noun))
    ? text[0].toLowerCase() + text.slice(1)
    : text;

function seoTitle(op: Operation): string {
  if (sourceName(op).toLowerCase() === endpointTitle(op).toLowerCase()) return `${sourceName(op)} API`;
  return `${sourceName(op)} ${lowerFirst(endpointTitle(op))} API`;
}

function propertiesOf(schema: Json | undefined): string[] {
  if (!isObject(schema)) return [];
  const item = schema.type === "array" ? schema.items : schema;
  if (!isObject(item)) return [];
  const own = Object.keys((item.properties as JsonObject | undefined) ?? {});
  const options = (item.allOf ?? item.oneOf ?? item.anyOf) as Json[] | undefined;
  const merged = Array.isArray(options) ? options.flatMap(propertiesOf) : [];
  return [...new Set([...own, ...merged])];
}

function seoDescription(op: Operation): string {
  const price = `${cost(op)} per call.`;
  const parts = [`${op.summary.replace(/\.$/, "")}.`, `Call the ${seoTitle(op)} and get JSON back in one request.`, price, "Failed calls cost nothing."];
  let text = parts.join(" ");
  if (text.length > 160) text = [parts[0], `Call the ${seoTitle(op)} for JSON.`, price].join(" ");
  if (text.length < 120) text = `${text} Every call returns the same flat shape.`;
  return text;
}

// How other pages name an endpoint in a link: "YouTube video", "Google Maps place".
const GOOGLE_PRODUCTS = ["Search", "News", "Images", "Videos", "Scholar", "Patents", "Maps", "Hotels", "Flights", "Jobs", "Shopping", "Trends", "AI Mode", "Play"];
function linkLabel(id: string): string {
  const named = config.labels[id];
  if (named !== undefined) return named;
  const source = config.sources[sourceOf(id.split("."))] ?? id;
  const title = config.titles[id] ?? id;
  const proper = source === "Google" && GOOGLE_PRODUCTS.some((product) => title.startsWith(product));
  return `${source} ${proper ? title : lowerFirst(title)}`;
}

function endpointPage(op: Operation): string {
  const title = op.id === "endpoints" ? "Endpoint catalog API" : seoTitle(op);
  const description = op.id === "endpoints" ? CATALOG_DESCRIPTION : seoDescription(op);
  const sidebar = op.id === "endpoints" ? "List Endpoints" : endpointTitle(op);
  const header = [
    "---",
    `title: '${quote(title)}'`,
    `sidebarTitle: '${sidebar}'`,
    `description: '${quote(description)}'`,
    `og:title: '${quote(title)} | Stophy'`,
    `og:description: '${quote(description)}'`,
    `openapi: '${SPEC_PATH} ${op.method} ${op.path}'`,
    "---",
    "",
  ];
  if (op.id === "endpoints") {
    return [...header, GENERATED, "", op.summary, ""].join("\n");
  }
  const endpoint = catalogById.get(op.id);
  if (endpoint === undefined) throw new Error(`${op.id} is not in the catalog`);
  const example = exampleSection(op);
  const response = JSON.parse(readFileSync(file(`scripts/responses/${op.id}.json`), "utf8")) as ExampleResponse;
  const text = body(
    {
      endpoint,
      catalog: catalogList,
      config,
      schema: op.data,
      creditsMax: op.creditsMax,
      response,
      slug: (id) => id.replaceAll(".", "-"),
      label: linkLabel,
      titleOf: (id) => config.titles[id] ?? id,
    },
    example.body,
  );
  return [...header, ...example.imports, "", GENERATED, "", ...text, ""].join("\n");
}

// Each endpoint has one example generated by builder-docs at
// snippets/examples/<id>/{ts,python,curl,cli}.mdx. Import all four and show
// them as tabs in one CodeGroup, in a fixed language order.
function exampleSection(op: Operation): { imports: string[]; body: string[]; length: number } {
  const dir = `/snippets/examples/${op.id}`;
  const langs: { file: string; component: string }[] = [
    { file: "ts", component: "TsExample" },
    { file: "python", component: "PythonExample" },
    { file: "curl", component: "CurlExample" },
    { file: "cli", component: "CliExample" },
  ];
  const imports = langs.map(({ file, component }) => `import ${component} from "${dir}/${file}.mdx";`);
  const body = ["<CodeGroup>", ...langs.map(({ component }) => `<${component} />`), "</CodeGroup>"];
  return { imports, body, length: 1 };
}

const ops = operations();
const byId = new Map(ops.map((op) => [op.id, op]));

const assigned = config.areas.flatMap((area) => area.endpoints);
const twice = assigned.filter((id, index) => assigned.indexOf(id) !== index);
if (twice.length > 0) throw new Error(`In more than one area in reference.config.json: ${twice.join(", ")}`);
const unknownTitles = Object.keys(config.titles).filter((id) => !byId.has(id));
if (unknownTitles.length > 0) throw new Error(`Titles for unknown endpoints in reference.config.json: ${unknownTitles.join(", ")}`);
const covered = new Set(assigned);
const missing = ops.filter((op) => op.method === "POST" && !covered.has(op.id)).map((op) => op.id);
if (missing.length > 0) throw new Error(`Not in any area in reference.config.json: ${missing.join(", ")}`);

const endpointDir = "api-reference/endpoint";
for (const existing of new Bun.Glob("*.mdx").scanSync(file(`${endpointDir}/`).pathname)) {
  await Bun.file(file(`${endpointDir}/${existing}`)).delete();
}
const pages = ops.map((op) => [op, endpointPage(op)] as const);
if (problems.length > 0) throw new Error(problems.join("\n"));
for (const [op, page] of pages) await Bun.write(file(`${endpointDir}/${op.slug}.mdx`), page);

const categoryGroups = config.areas.map((area) => {
  const sources: string[] = [];
  for (const id of area.endpoints) {
    const op = byId.get(id);
    if (op !== undefined && !sources.includes(op.source)) sources.push(op.source);
  }
  return {
    group: area.title,
    icon: area.icon,
    pages: sources.map((source) => ({
      group: config.sources[source] ?? source,
      pages: area.endpoints
        .map((id) => byId.get(id))
        .filter((op): op is Operation => op !== undefined && op.source === source)
        .map((op) => `${endpointDir}/${op.slug}`),
    })),
  };
});

const docs = (await Bun.file(file("docs.json")).json()) as JsonObject;
const tabs = (docs.navigation as JsonObject).tabs as JsonObject[];
const reference = tabs.find((tab) => tab.tab === "API Reference");
if (reference === undefined) throw new Error("docs.json needs the API Reference tab");
const fixed = (reference.groups as JsonObject[]).filter((group) =>
  ["Using the API", "Catalog", "Account"].includes(String(group.group)),
);
const catalogGroup = fixed.find((group) => group.group === "Catalog");
if (catalogGroup !== undefined) catalogGroup.pages = [`${endpointDir}/endpoints`];
reference.groups = [...fixed, ...categoryGroups];
await Bun.write(file("docs.json"), `${JSON.stringify(docs, null, 2)}\n`);

console.log(`Wrote ${ops.length} endpoint pages and ${categoryGroups.length} reference groups.`);
