// Generates the 10 "What you can get" category pages (sources/*.mdx) from the
// live catalog and the snippets in snippets/examples/. Run with:
//   bun scripts/gen-examples.ts && bun scripts/gen-sources.ts
// Every file it writes is overwritten on each run: change AREAS below, not the
// output. This script owns sources/*.mdx; it does not touch the API reference
// pages or scripts/reference.config.json, which belong to gen-reference.ts.

import { type CatalogEndpoint, type Json, type JsonObject, fetchCatalog, isObject } from "./catalog";

const root = new URL("..", import.meta.url);
const file = (path: string) => new URL(path, root);
const SPEC_PATH = "api-reference/openapi.json";
const PLAYGROUND = "https://stophy.dev/playground";
const GENERATED =
  "{/* Generated by scripts/gen-sources.ts from the live catalog. Do not edit by hand: change the config in that script and rerun it. */}";

interface Area {
  title: string;
  slug: string;
  icon: string;
  description: string;
  endpoints: string[];
  example: string;
  variations: string[];
  tip: string;
}

// One row per category in the Documentation tab's "What you can get" group.
// `endpoints` lists every catalog id that belongs on this page (checked below:
// every POST endpoint must appear on exactly one page). `example` is the call
// shown first; `variations` are 2-3 more calls shown further down the page.
const AREAS: Area[] = [
  {
    title: "Web search and pages",
    slug: "web",
    icon: "globe",
    description:
      "Search the web and the news, and pull contacts, sitemaps, and SEO tags from a site. Look up domain and email details, plus Google's autocomplete and trends.",
    endpoints: [
      "web.search",
      "web.news",
      "web.contacts",
      "site.map",
      "site.seo",
      "domain.whois",
      "domain.dns",
      "domain.tech",
      "email.check",
      "google.suggest",
      "google.trends.interest",
      "google.trends.regions",
      "google.trends.related",
      "google.trends.trending",
    ],
    example: "web.search",
    variations: ["site.map", "domain.whois"],
    tip: "Send `accept: text/markdown` to any of these endpoints to get a readable page instead of JSON. See [Get markdown for a model](/guides/markdown).",
  },
  {
    title: "Video",
    slug: "video",
    icon: "video",
    description:
      "Search YouTube, TikTok, and Kick, and open any video, channel, or playlist. Get transcripts, comments, and clip details as JSON or markdown.",
    endpoints: [
      "youtube.search",
      "youtube.video",
      "youtube.transcript",
      "youtube.comments",
      "youtube.comments.replies",
      "youtube.channel",
      "youtube.playlist",
      "youtube.suggest",
      "tiktok.profile",
      "tiktok.video",
      "tiktok.url",
      "tiktok.transcript",
      "tiktok.posts",
      "tiktok.hashtag",
      "tiktok.comments",
      "tiktok.comments.replies",
      "tiktok.search",
      "kick.channel",
      "kick.videos",
      "kick.clips",
    ],
    example: "youtube.search",
    variations: ["youtube.transcript", "tiktok.profile", "kick.channel"],
    tip: "YouTube search, YouTube transcripts, and web search work without a key. Every other endpoint on this page needs one.",
  },
  {
    title: "Social",
    slug: "social",
    icon: "users",
    description:
      "Search and read posts, profiles, and comments across Reddit, Instagram, X, LinkedIn, and eight more networks. Get replies and followers as JSON.",
    endpoints: [
      "reddit.search",
      "reddit.post",
      "reddit.comments.more",
      "reddit.subreddit",
      "reddit.user",
      "reddit.domain",
      "instagram.profile",
      "instagram.posts",
      "instagram.post",
      "instagram.url",
      "instagram.search",
      "instagram.transcript",
      "instagram.comments",
      "instagram.comments.replies",
      "x.tweet",
      "threads.profile",
      "threads.posts",
      "threads.post",
      "threads.search",
      "bluesky.profile",
      "bluesky.posts",
      "bluesky.post",
      "bluesky.followers",
      "mastodon.profile",
      "mastodon.posts",
      "mastodon.post",
      "mastodon.hashtag",
      "telegram.channel",
      "telegram.posts",
      "telegram.post",
      "linkedin.company",
      "linkedin.profile",
      "linkedin.posts",
      "linkedin.company.posts",
      "pinterest.search",
      "pinterest.pin",
      "pinterest.board",
      "pinterest.user",
      "tumblr.blog",
      "tumblr.posts",
      "tumblr.post",
      "tumblr.search",
      "snapchat.profile",
      "quora.question",
    ],
    example: "reddit.search",
    variations: ["instagram.profile", "x.tweet", "linkedin.profile"],
    tip: "Endpoints that return a list, like Reddit search and Instagram posts, page. See [Page through results](/guides/paging).",
  },
  {
    title: "Places and travel",
    slug: "places-and-travel",
    icon: "map-location-dot",
    description:
      "Find places on Google Maps with their reviews, and search flights on Google Travel. Get stays, calendars, and reviews from Tripadvisor and Airbnb.",
    endpoints: [
      "maps.search",
      "maps.place",
      "maps.reviews",
      "googletravel.flights",
      "tripadvisor.search",
      "tripadvisor.place",
      "tripadvisor.reviews",
      "airbnb.search",
      "airbnb.listing",
      "airbnb.calendar",
      "airbnb.reviews",
    ],
    example: "maps.search",
    variations: ["tripadvisor.search", "airbnb.search"],
    tip: "Pass the place id from a Google Maps search, the id from a Tripadvisor search, or the listing URL from an Airbnb search into that source's other endpoints.",
  },
  {
    title: "Shopping",
    slug: "shopping",
    icon: "cart-shopping",
    description:
      "Search Amazon, Walmart, AliExpress, and any Shopify store. Get products, prices, bestsellers, and collections as structured JSON.",
    endpoints: [
      "amazon.search",
      "amazon.product",
      "amazon.bestsellers",
      "amazon.suggest",
      "walmart.search",
      "walmart.product",
      "aliexpress.search",
      "aliexpress.product",
      "shopify.products",
      "shopify.collections",
      "shopify.store",
    ],
    example: "amazon.search",
    variations: ["walmart.search", "shopify.products"],
    tip: "Pass the product URL from a search result into the Amazon, Walmart, or AliExpress product lookup for full pricing and details.",
  },
  {
    title: "Apps",
    slug: "apps",
    icon: "mobile",
    description: "Look up apps on the App Store and Google Play. Get listings, top charts, and user reviews as structured JSON or markdown.",
    endpoints: ["appstore.app", "appstore.search", "appstore.reviews", "appstore.top", "googleplay.app", "googleplay.search", "googleplay.reviews"],
    example: "appstore.search",
    variations: ["appstore.app", "googleplay.search"],
    tip: "Pass the app id from a search result into the App Store or Google Play reviews endpoint to read what users say.",
  },
  {
    title: "Jobs",
    slug: "jobs",
    icon: "briefcase",
    description: "Search job listings on LinkedIn, Upwork, and Indeed. Get the full posting, pay, and requirements for any job as JSON or markdown.",
    endpoints: ["linkedin.jobs.search", "linkedin.jobs.job", "upwork.search", "upwork.job", "indeed.search", "indeed.job"],
    example: "linkedin.jobs.search",
    variations: ["upwork.search", "indeed.search"],
    tip: "Pass the job URL from a search result into that site's job lookup endpoint for the full posting.",
  },
  {
    title: "Real estate",
    slug: "real-estate",
    icon: "house",
    description: "Search homes for sale and rent on Zillow, Redfin, Realtor.com, Rightmove, and ImmoScout24. Get price, photos, and details for any listing.",
    endpoints: [
      "zillow.search",
      "zillow.property",
      "redfin.search",
      "redfin.property",
      "realtor.search",
      "realtor.property",
      "rightmove.search",
      "rightmove.property",
      "immoscout.search",
      "immoscout.listing",
    ],
    example: "zillow.search",
    variations: ["redfin.search", "realtor.search"],
    tip: "Pass the listing URL from a search result into that site's property endpoint for the full listing.",
  },
  {
    title: "Ads",
    slug: "ads",
    icon: "bullhorn",
    description: "Search the public ad libraries of Meta, Google, TikTok, LinkedIn, Pinterest, Microsoft, and Snapchat. Get each ad's creative and copy.",
    endpoints: [
      "meta.ads.search",
      "meta.ads.page",
      "meta.ads.ad",
      "google.ads.advertisers",
      "google.ads.search",
      "google.ads.ad",
      "tiktok.ads.search",
      "tiktok.ads.ad",
      "linkedin.ads.search",
      "linkedin.ads.ad",
      "pinterest.ads.search",
      "pinterest.ads.ad",
      "microsoft.ads.search",
      "microsoft.ads.ad",
      "microsoft.ads.advertisers",
      "snapchat.ads.search",
      "snapchat.ads.ad",
    ],
    example: "meta.ads.search",
    variations: ["google.ads.search", "tiktok.ads.search"],
    tip: "Every ad library needs a keyword, an advertiser, or both. See each endpoint's reference for what it accepts.",
  },
  {
    title: "Finance and crypto",
    slug: "finance-and-crypto",
    icon: "chart-line",
    description: "Get stock quotes, price history, and company profiles. Get crypto prices, trending coins, DEX pairs, new tokens, wallets, and token holders.",
    endpoints: [
      "finance.quote",
      "finance.history",
      "finance.search",
      "finance.profile",
      "crypto.coins",
      "crypto.coin",
      "crypto.history",
      "crypto.trending",
      "crypto.categories",
      "crypto.movers",
      "crypto.new",
      "crypto.dex.search",
      "crypto.dex.pairs",
      "crypto.dex.token",
      "crypto.dex.new",
      "crypto.pump.coins",
      "crypto.pump.coin",
      "crypto.pump.trades",
      "crypto.wallet",
      "crypto.token.holders",
      "crypto.binance.announcements",
    ],
    example: "finance.quote",
    variations: ["crypto.coins", "crypto.trending"],
    tip: "Stock quotes accept several tickers in one call. Coin prices accept several coin ids.",
  },
];

// Real, verified output from a keyless call made while writing this page (see
// the docs repo's builder report for the exact command). Used instead of a
// schema-guessed sample for the endpoints that actually answer without a key.
const LIVE_RESPONSES: Record<string, JsonObject> = {
  "web.search": {
    success: true,
    data: {
      results: [
        {
          title: "Top 10 Project Management Software I Tested & Recommend for 2026",
          url: "https://project-management.com/top-10-project-management-software/",
          description:
            "2 weeks ago - The best project management software is monday.com for visual planning and beginners, ClickUp for task hierarchies, Jira for agile software delivery, Asana for workflow automation, and Teamwork for professional services.",
          domain: "project-management.com",
          position: 1,
        },
        {
          title: "10 Best Project Management Software Picked For 2026",
          url: "https://thedigitalprojectmanager.com/tools/best-project-management-software/",
          description:
            "4 days ago - Project management software earns its place when it gives teams real visibility, handles resource planning, and scales with your workload. I evaluated 40 options.",
          domain: "thedigitalprojectmanager.com",
          position: 2,
        },
      ],
    },
    creditsUsed: 0,
    requestId: "08a1799a-c64c-4d69-a39f-34fe91139d31",
  },
  "youtube.search": {
    success: true,
    data: {
      results: [
        {
          type: "video",
          id: "Wc0ZJo06oAw",
          url: "https://www.youtube.com/watch?v=Wc0ZJo06oAw",
          title: "The Ultimate Rust Beginners Guide (2026)",
          channel: {
            id: "UCt6XPuD8u3YjvybuT-Xnj5A",
            username: "SBJake",
            name: "SBJake",
            url: "https://www.youtube.com/channel/UCt6XPuD8u3YjvybuT-Xnj5A",
          },
          durationSeconds: 422,
          views: 543208,
          thumbnail: "https://i.ytimg.com/vi/Wc0ZJo06oAw/hqdefault.jpg",
          isShort: false,
          isLive: false,
          createdAt: "2025-09-28T13:19:10.000Z",
        },
        {
          type: "video",
          id: "5C_HPTJg5ek",
          url: "https://www.youtube.com/watch?v=5C_HPTJg5ek",
          title: "Rust in 100 Seconds",
          channel: {
            id: "UCsBjURrPoezykLs9EqgamOA",
            username: "Fireship",
            name: "Fireship",
            url: "https://www.youtube.com/channel/UCsBjURrPoezykLs9EqgamOA",
          },
          durationSeconds: 149,
          views: 2518131,
          thumbnail: "https://i.ytimg.com/vi/5C_HPTJg5ek/hqdefault.jpg",
          isShort: false,
          isLive: false,
          createdAt: "2022-09-28T19:51:34.000Z",
        },
      ],
    },
    creditsUsed: 0,
    requestId: "5fb0898a-3983-4f30-ae3e-3146c406ccd1",
  },
  "youtube.transcript": {
    success: true,
    data: {
      id: "dQw4w9WgXcQ",
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      language: "en",
      isAutoGenerated: false,
      durationSeconds: 213,
      text: "[♪♪♪] ♪ We're no strangers to love ♪ ♪ You know the rules and so do I ♪ ♪ A full commitment's what I'm thinking of ♪ …",
    },
    creditsUsed: 0,
    requestId: "e35872a1-7243-403c-8fb8-dfced0f0ee77",
  },
};

// --- schema-based sample responses, for endpoints that need a key ----------

function stringSample(key: string, format: string | undefined, enumValues: readonly Json[] | undefined): string {
  if (Array.isArray(enumValues) && typeof enumValues[0] === "string") return enumValues[0];
  const k = key.toLowerCase();
  if (k.includes("thumbnail") || k.includes("image") || k.includes("photo") || k.includes("avatar")) return "https://example.com/image.jpg";
  if (k === "url" || k.endsWith("url")) return "https://example.com/";
  if (format === "date-time") return "2026-09-28T12:00:00.000Z";
  if (format === "date") return "2026-09-28";
  if (format === "uri") return "https://example.com/";
  if (k === "id" || k.endsWith("id")) return "abc123";
  if (k === "email") return "person@example.com";
  if (k === "domain") return "example.com";
  if (k === "currency") return "USD";
  if (k === "country") return "us";
  if (k === "language") return "en";
  if (k === "username" || k === "handle") return "example";
  if (k === "title" || k === "name") return "Example title";
  if (k === "description" || k === "summary" || k === "snippet" || k === "text" || k === "bio") return "A short, readable summary of the result.";
  if (k === "price") return "19.99";
  return "example";
}

function numberSample(key: string): number {
  const k = key.toLowerCase();
  if (k.includes("price") || k.includes("amount")) return 19.99;
  if (k.includes("view") || k.includes("count") || k.includes("like") || k.includes("follower") || k.includes("total")) return 1234;
  if (k === "position" || k === "rank" || k === "page") return 1;
  if (k.includes("duration") || k.includes("seconds")) return 120;
  if (k.includes("rating") || k.includes("score")) return 4.5;
  return 1;
}

function sampleFor(schema: Json | undefined, key: string): Json {
  if (!isObject(schema)) return null;
  if (schema.const !== undefined) return schema.const;
  const enumValues = schema.enum as Json[] | undefined;
  if (Array.isArray(enumValues) && enumValues.length > 0) return enumValues[0] ?? null;
  const options = (schema.oneOf ?? schema.anyOf) as Json[] | undefined;
  if (Array.isArray(options) && options.length > 0) return sampleFor(options[0], key);
  if (schema.type === "array") return [sampleFor(schema.items as Json | undefined, key)];
  if (schema.type === "object") {
    const props = (schema.properties as JsonObject | undefined) ?? {};
    const obj: JsonObject = {};
    for (const [field, sub] of Object.entries(props)) {
      if (field === "cursor") continue;
      obj[field] = sampleFor(sub, field);
    }
    return obj;
  }
  if (schema.type === "string") return stringSample(key, schema.format as string | undefined, schema.enum as Json[] | undefined);
  if (schema.type === "integer" || schema.type === "number") return numberSample(key);
  if (schema.type === "boolean") return false;
  return null;
}

function dataSchema(op: CatalogEndpoint, spec: JsonObject): Json | undefined {
  const item = (spec.paths as JsonObject | undefined)?.[op.path];
  if (!isObject(item)) return undefined;
  const operation = item[op.method.toLowerCase()];
  if (!isObject(operation)) return undefined;
  const ok = ((operation.responses as JsonObject | undefined)?.["200"] as JsonObject | undefined)?.content as JsonObject | undefined;
  const envelope = (ok?.["application/json"] as JsonObject | undefined)?.schema as JsonObject | undefined;
  return (envelope?.properties as JsonObject | undefined)?.data;
}

function responseSample(op: CatalogEndpoint, spec: JsonObject): JsonObject {
  const live = LIVE_RESPONSES[op.id];
  if (live !== undefined) return live;
  const data = sampleFor(dataSchema(op, spec), "data");
  return { success: true, data, creditsUsed: op.credits ?? 1, requestId: crypto.randomUUID() };
}

// --- page rendering ---------------------------------------------------

const slugOf = (id: string) => id.split(".").join("-");
const importOf = (id: string, lang: string) =>
  `${id
    .split(".")
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join("")}${lang[0]?.toUpperCase()}${lang.slice(1)}`;

function creditPhrase(op: CatalogEndpoint): string {
  if (op.credits === undefined || op.credits === null) return "Free";
  const noun = op.credits === 1 ? "credit" : "credits";
  const base = `${op.credits} ${noun}`;
  const cost = op.perItems === undefined || op.perItems === null ? base : `${base} per ${op.perItems} items, at least ${base}`;
  return op.keyless ? `${cost} (no key needed)` : cost;
}

function codeGroupImports(id: string): string {
  return (["ts", "python", "curl", "cli"] as const)
    .map((lang) => `import ${importOf(id, lang)} from '/snippets/examples/${id}/${lang}.mdx';`)
    .join("\n");
}

function codeGroup(id: string): string {
  const tags = (["ts", "python", "curl", "cli"] as const).map((lang) => `  <${importOf(id, lang)} />`);
  return ["<CodeGroup>", ...tags, "</CodeGroup>"].join("\n");
}

function areaPage(area: Area, byId: Map<string, CatalogEndpoint>, spec: JsonObject): string {
  const example = byId.get(area.example);
  if (example === undefined) throw new Error(`${area.title}: example ${area.example} is not in the catalog`);
  for (const id of [area.example, ...area.variations]) {
    if (!byId.has(id)) throw new Error(`${area.title}: ${id} is not in the catalog`);
  }

  const rows = area.endpoints.map((id) => {
    const op = byId.get(id);
    if (op === undefined) throw new Error(`${area.title}: ${id} is not in the catalog`);
    return `| [${op.summary}](/api-reference/endpoint/${slugOf(id)}) | ${creditPhrase(op)} |`;
  });

  const allImports = [area.example, ...area.variations].map(codeGroupImports).join("\n");

  const variationSections = area.variations.map((id) => {
    const op = byId.get(id);
    if (op === undefined) throw new Error(`${area.title}: ${id} is not in the catalog`);
    return [`### ${op.summary}`, "", codeGroup(id), ""].join("\n");
  });

  return [
    "---",
    `title: '${area.title.replaceAll("'", "''")}'`,
    `description: '${area.description.replaceAll("'", "''")}'`,
    `og:title: '${area.title.replaceAll("'", "''")} | Stophy'`,
    `og:description: '${area.description.replaceAll("'", "''")}'`,
    `icon: '${area.icon}'`,
    "---",
    "",
    GENERATED,
    "",
    allImports,
    "",
    `${area.description} See every field in the [${area.title} reference](/api-reference/endpoint/${slugOf(area.example)}), or try it in the [playground](${PLAYGROUND}).`,
    "",
    `## ${example.summary}`,
    "",
    codeGroup(area.example),
    "",
    "The response:",
    "",
    "```json",
    JSON.stringify(responseSample(example, spec), null, 2),
    "```",
    "",
    "## Endpoints",
    "",
    "| Endpoint | Cost |",
    "| --- | --- |",
    ...rows,
    "",
    "## More ways to call it",
    "",
    ...variationSections,
    `<Tip>${area.tip}</Tip>`,
    "",
  ].join("\n");
}

// --- main -----------------------------------------------------------------

const catalog = await fetchCatalog();
const spec = (await Bun.file(file(SPEC_PATH)).json()) as JsonObject;
const byId = new Map(catalog.endpoints.map((op) => [op.id, op]));

const assigned = AREAS.flatMap((area) => area.endpoints);
const twice = assigned.filter((id, index) => assigned.indexOf(id) !== index);
if (twice.length > 0) throw new Error(`In more than one area: ${twice.join(", ")}`);
const covered = new Set(assigned);
const missing = catalog.endpoints.filter((op) => op.method === "POST" && !covered.has(op.id)).map((op) => op.id);
if (missing.length > 0) throw new Error(`Not in any area: ${missing.join(", ")}`);

for (const area of AREAS) await Bun.write(file(`sources/${area.slug}.mdx`), areaPage(area, byId, spec));

console.log(`Wrote ${AREAS.length} category pages covering ${assigned.length} endpoints.`);
