// Generates the API reference pages, the source pages and their navigation
// from the vendored spec (api-reference/openapi.json) and
// scripts/reference.config.json. Run with `bun scripts/gen-reference.ts`.
// Every file it writes is overwritten on each run: edit the config, not the output.

type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
type JsonObject = { [key: string]: Json };

interface Area {
  title: string;
  slug: string;
  icon: string;
  intro: string;
  endpoints: string[];
  example: string;
  live?: { input: JsonObject; response: Json };
}

interface Config {
  sources: Record<string, string>;
  areas: Area[];
  notes: Record<string, string>;
}

interface Operation {
  id: string;
  method: "GET" | "POST";
  path: string;
  slug: string;
  source: string;
  credits: number | undefined;
  perItems: number | undefined;
  pages: boolean;
  input: JsonObject | undefined;
  example: JsonObject | undefined;
  data: JsonObject | undefined;
}

const root = new URL("..", import.meta.url);
const file = (path: string) => new URL(path, root);
const SPEC_PATH = "api-reference/openapi.json";
const GENERATED = "{/* Generated by scripts/gen-reference.ts from api-reference/openapi.json. Do not edit. */}";

const spec = (await Bun.file(file(SPEC_PATH)).json()) as JsonObject;
const config = (await Bun.file(file("scripts/reference.config.json")).json()) as Config;

const isObject = (value: Json | undefined): value is JsonObject =>
  typeof value === "object" && value !== null && !Array.isArray(value);

function operations(): Operation[] {
  const paths = spec.paths as JsonObject;
  const list: Operation[] = [];
  for (const [path, item] of Object.entries(paths)) {
    if (!isObject(item)) continue;
    for (const [method, op] of Object.entries(item)) {
      if (!isObject(op)) continue;
      const parts = path.replace(/^\/v1\//, "").split("/");
      const id = parts.join(".");
      const body = (op.requestBody as JsonObject | undefined)?.content as JsonObject | undefined;
      const json = body?.["application/json"] as JsonObject | undefined;
      const input = json?.schema as JsonObject | undefined;
      const example = isObject(json?.example) ? json.example : undefined;
      const ok = ((op.responses as JsonObject)["200"] as JsonObject | undefined)?.content as JsonObject | undefined;
      const envelope = (ok?.["application/json"] as JsonObject | undefined)?.schema as JsonObject | undefined;
      const data = (envelope?.properties as JsonObject | undefined)?.data as JsonObject | undefined;
      list.push({
        id,
        method: method.toUpperCase() as "GET" | "POST",
        path,
        slug: parts.join("-"),
        source: parts[0] ?? id,
        credits: typeof op["x-credits"] === "number" ? op["x-credits"] : undefined,
        perItems: typeof op["x-per-items"] === "number" ? op["x-per-items"] : undefined,
        pages: isObject((input?.properties as JsonObject | undefined)?.cursor),
        input,
        example,
        data,
      });
    }
  }
  return list;
}

const plural = (count: number, word: string) => `${count} ${word}${count === 1 ? "" : "s"}`;

function cost(op: Operation): string {
  if (op.credits === undefined) return "Free";
  const base = plural(op.credits, "credit");
  return op.perItems === undefined ? base : `${base} per ${op.perItems} items, at least ${base}`;
}

function typeOf(schema: Json | undefined): string {
  if (!isObject(schema)) return "any";
  if ("const" in schema) return JSON.stringify(schema.const);
  if (Array.isArray(schema.enum)) return schema.enum.map((value) => JSON.stringify(value)).join(" \\| ");
  if (Array.isArray(schema.oneOf) || Array.isArray(schema.anyOf)) {
    const options = (schema.oneOf ?? schema.anyOf) as Json[];
    return [...new Set(options.map(typeOf))].join(" \\| ");
  }
  if (schema.type === "array") return `${typeOf(schema.items)}[]`;
  if (Array.isArray(schema.type)) return schema.type.join(" \\| ");
  if (typeof schema.type === "string") return schema.type;
  return "any";
}

function variants(data: JsonObject): string[] {
  const options = (data.oneOf ?? data.anyOf) as Json[] | undefined;
  if (!Array.isArray(options)) return [];
  return options.flatMap((option) => {
    const kind = isObject(option) ? (option.properties as JsonObject | undefined)?.kind : undefined;
    return isObject(kind) && typeof kind.const === "string" ? [kind.const] : [];
  });
}

function returns(op: Operation): string {
  if (op.data === undefined) return "";
  const fields = Object.keys((op.data.properties as JsonObject | undefined) ?? {}).filter(
    (field) => field !== "cursor",
  );
  if (fields.length > 0) return `\`data\` has ${fields.map((field) => `\`${field}\``).join(", ")}.`;
  const kinds = variants(op.data);
  if (kinds.length === 0) return "";
  return `\`data\` is one of ${kinds.map((kind) => `\`${kind}\``).join(", ")}. \`data.kind\` says which.`;
}

function fieldRows(op: Operation): string[] {
  const properties = (op.data?.properties as JsonObject | undefined) ?? {};
  const rows: string[] = [];
  for (const [field, schema] of Object.entries(properties)) {
    rows.push(`| \`${field}\` | \`${typeOf(schema)}\` |`);
    const item = isObject(schema) && schema.type === "array" ? schema.items : schema;
    const nested = isObject(item) && item.type === "object" ? (item.properties as JsonObject | undefined) : undefined;
    const prefix = isObject(schema) && schema.type === "array" ? `${field}[]` : field;
    for (const [child, childSchema] of Object.entries(nested ?? {})) {
      rows.push(`| \`${prefix}.${child}\` | \`${typeOf(childSchema)}\` |`);
    }
  }
  return rows;
}

function endpointPage(op: Operation): string {
  const title = op.id === "endpoints" ? "Endpoint catalog" : op.id;
  const sidebar = op.id === "endpoints" ? "List endpoints" : op.id.split(".").slice(1).join(".");
  const paging = op.pages
    ? `Yes. Send the \`cursor\` from the response to get the next page. See [Paging](/advanced-guide#paging).`
    : "No.";
  const facts = [
    returns(op) === "" ? undefined : `- **Returns:** ${returns(op)}`,
    `- **Cost:** ${cost(op)}.${op.credits !== undefined ? " Failed calls cost nothing." : ""}`,
    op.method === "POST" ? `- **Paging:** ${paging}` : undefined,
  ].filter((line) => line !== undefined);
  const note = config.notes[op.id];
  return [
    "---",
    `title: '${title}'`,
    `sidebarTitle: '${sidebar}'`,
    `openapi: '${SPEC_PATH} ${op.method} ${op.path}'`,
    "---",
    "",
    GENERATED,
    "",
    ...facts,
    ...(note === undefined ? [] : ["", note]),
    "",
  ].join("\n");
}

function curl(op: Operation, input: JsonObject): string {
  const body = JSON.stringify(input);
  return [
    "```bash",
    `curl -X POST https://api.stophy.dev${op.path} \\`,
    '  -H "Authorization: Bearer $STOPHY_API_KEY" \\',
    '  -H "content-type: application/json" \\',
    `  -d '${body.replaceAll("'", "'\\''")}'`,
    "```",
  ].join("\n");
}

function areaPage(area: Area, byId: Map<string, Operation>): string {
  const rows = area.endpoints.map((id) => {
    const op = byId.get(id);
    if (op === undefined) throw new Error(`${area.title}: ${id} is not in the spec`);
    return `| [\`${id}\`](/api-reference/endpoint/${op.slug}) | ${cost(op)} | ${op.pages ? "Yes" : "No"} |`;
  });
  const example = byId.get(area.example);
  if (example === undefined) throw new Error(`${area.title}: example ${area.example} is not in the spec`);
  const input = area.live?.input ?? example.example;
  if (!isObject(input)) throw new Error(`${area.title}: ${example.id} has no example input`);
  const response = area.live
    ? [
        "The response to this exact request:",
        "",
        "```json",
        JSON.stringify(area.live.response, null, 2),
        "```",
      ]
    : [
        `The fields in \`data\`, from the [${example.id} reference](/api-reference/endpoint/${example.slug}):`,
        "",
        "| Field | Type |",
        "| --- | --- |",
        ...fieldRows(example),
      ];
  return [
    "---",
    `title: '${area.title}'`,
    `description: '${area.intro.replaceAll("'", "''")}'`,
    `icon: '${area.icon}'`,
    "---",
    "",
    GENERATED,
    "",
    "## Endpoints",
    "",
    "| Endpoint | Cost | Paging |",
    "| --- | --- | --- |",
    ...rows,
    "",
    `## Example: ${example.id}`,
    "",
    curl(example, input),
    "",
    ...response,
    "",
    `Send \`accept: text/markdown\` to get the same data as a readable page. See the [advanced guide](/advanced-guide#markdown-output).`,
    "",
  ].join("\n");
}

const ops = operations();
const byId = new Map(ops.map((op) => [op.id, op]));

const covered = new Set(config.areas.flatMap((area) => area.endpoints));
const missing = ops.filter((op) => op.method === "POST" && !covered.has(op.id)).map((op) => op.id);
if (missing.length > 0) throw new Error(`Not in any area in reference.config.json: ${missing.join(", ")}`);

const endpointDir = "api-reference/endpoint";
for (const existing of new Bun.Glob("*.mdx").scanSync(file(`${endpointDir}/`).pathname)) {
  await Bun.file(file(`${endpointDir}/${existing}`)).delete();
}
for (const op of ops) await Bun.write(file(`${endpointDir}/${op.slug}.mdx`), endpointPage(op));

for (const existing of new Bun.Glob("*.mdx").scanSync(file("sources/").pathname)) {
  await Bun.file(file(`sources/${existing}`)).delete();
}
for (const area of config.areas) await Bun.write(file(`sources/${area.slug}.mdx`), areaPage(area, byId));

const sourceOrder: string[] = [];
for (const op of ops) if (op.method === "POST" && !sourceOrder.includes(op.source)) sourceOrder.push(op.source);
const sourceGroups = sourceOrder.map((source) => {
  const name = config.sources[source];
  if (name === undefined) throw new Error(`No display name for source ${source}`);
  return {
    group: name,
    pages: ops.filter((op) => op.source === source && op.method === "POST").map((op) => `${endpointDir}/${op.slug}`),
  };
});

const docs = (await Bun.file(file("docs.json")).json()) as JsonObject;
const tabs = (docs.navigation as JsonObject).tabs as JsonObject[];
const documentation = tabs.find((tab) => tab.tab === "Documentation");
const reference = tabs.find((tab) => tab.tab === "API Reference");
if (documentation === undefined || reference === undefined) throw new Error("docs.json needs the Documentation and API Reference tabs");
const sourcesGroup = (documentation.groups as JsonObject[]).find((group) => group.group === "Sources");
if (sourcesGroup === undefined) throw new Error('docs.json needs a "Sources" group in Documentation');
sourcesGroup.pages = config.areas.map((area) => `sources/${area.slug}`);
const fixed = (reference.groups as JsonObject[]).filter((group) =>
  ["Using the API", "Catalog", "Account"].includes(String(group.group)),
);
const catalogGroup = fixed.find((group) => group.group === "Catalog");
if (catalogGroup !== undefined) catalogGroup.pages = [`${endpointDir}/endpoints`];
reference.groups = [...fixed, ...sourceGroups];
await Bun.write(file("docs.json"), `${JSON.stringify(docs, null, 2)}\n`);

console.log(
  `Wrote ${ops.length} endpoint pages, ${config.areas.length} source pages and ${sourceGroups.length} reference groups.`,
);
